### ISSUE TITLE
gxds/cache should remove dependency on ProtocolHandler

### ISSUE THREAD

**Issue by anonymouse64** [tonyespy/gxds#1]
I'm not sure why the cache package needs the `proto` member [here](https://github.com/tonyespy/gxds/blob/master/cache/devices.go#L31) 

If we remove this dependency as it doesn't seem to be used anywhere in the cache package we can move the ProtocolHandler interface into the `gxds/service` package where that interface is actually used.

Also I note that it may be necessary for some of the functions in objects.go (i.e. [this comment](https://github.com/tonyespy/gxds/blob/master/cache/objects.go#L36)), but I'm not familiar enough with the original codebase to say whether these functions need it or not...

**Comment by tonyespy** [comment]
proto is actually a ProtocolDriver, not a ProtocolHandler, but you're right it's not needed here, and I will remove it.  The Java DeviceStore code did called ProtocolHandler.initiazeDevice(), however I haven't found an actual need for a ProtocolHandler interface per so, I most likely will remove it altogether.

I also added a new sub-section to my device services requirements under 'devices', called 'initialization & disconnection', so this was a useful exercise.

**Comment by tonyespy** [comment]
Fixed here:

https://github.com/tonyespy/gxds/commit/a23df1bb729ddae08cd07679b3db5b7055676804
